# -*- coding: utf-8 -*-
"""All content for Issues No. 02-11, both editions. Data only - src/build_site.py renders it.

Every issue has the same shape, which is the point: a parent can find the same
thing in the same place every time. Keep prose short. The long-form treatment
lives in Issue No. 01; these are meant to be read the night before.
"""

ISSUES = [

dict(no="02", slug="a-phone", title="A phone", ask="So you want a phone",
 ages=(10,13), band="Usually 10&ndash;13", colour="pink",
 thesis="A phone is not one decision, it is <b>four</b>: a device, a phone number, an open internet, and an app store. They arrive in the same box, so most families hand over all four at once. You can grant them separately, and separating them is the whole game.",
 deciding=dict(q="Not <em>are they responsible enough</em>. It is: are they ready to be reachable by anybody, at any hour, with no adult in the room?",
   bullets=["Which of the four you are actually giving","Where it sleeps","Who is allowed to contact them"]),
 facts=["Whatever rule you set on day one is simply how phones work in this house. The same rule introduced six months later is a punishment for something, and will be argued with as one.",
        "The bedroom is the whole ballgame. A phone that charges in the kitchen removes most of what parents are actually afraid of, and it costs you one conversation instead of a hundred."],
 scripts=[dict(role="Say", say="You can have a phone. It is for calling and texting us and your friends. The internet and apps are a separate conversation, and we will have it in six months.",
               why="Two grants, not four. The other two are not refused, they are scheduled."),
          dict(role="And when the six months come", say="Right, apps. Which three, and what does each one do? Pick three and we will start there.",
               why="Three chosen apps is a decision they participated in. An open store is not.")],
 dont=dict(say="If your grades slip I am taking it away.",
   why="The moment the phone is the currency for everything else, every conversation in your house becomes a phone conversation - homework, chores, moods, all of it. Keep the phone rules about the phone."),
 rule=dict(text="The phone sleeps outside the bedroom. Everyone&rsquo;s does, including yours.",
   why="It is nearly frictionless on day one and nearly impossible to introduce later. It also happens to be the single rule that protects sleep, which is the thing that actually degrades first."),
 ready=[dict(t="They can be bored for ten minutes without reaching for something", why="Not a character test. A genuine predictor of how the phone gets used."),
        dict(t="They have told you about something that went wrong, unprompted", why="The channel matters more than the rules. If it is not open before the phone, the phone will not open it."),
        dict(t="They can hand it over when asked, without a scene", why="Try this with a borrowed device for a week first."),
        dict(t="You have decided where it charges at night", why="Decide before, not after. See the one rule.")],
 notyet="Start with a phone that only calls and texts. Put the date for the apps conversation in the calendar, in front of them, and keep it.",
 depth=[("What each of the four actually costs you",
   ["<strong>The device</strong> is the least of it. A phone that only makes calls solves the entire problem you started with, which was usually 'I need to reach them after football'.",
    "<strong>The number</strong> means anyone who has it can reach them at 11pm. Worth knowing who has it.",
    "<strong>The open internet</strong> is the one people mean when they say 'a phone'. It is a browser, and a browser is everything.",
    "<strong>The app store</strong> is a different thing again: it is the ability to install a new social world overnight, without telling you. This is the grant to give last and slowest."]),
  ("The handover conversation, in four minutes",
   ["Do it once, calmly, with the phone on the table between you rather than in their hands. Say what it is for. Say where it sleeps. Say what you will do if something goes wrong - and make that sentence generous, because it is the sentence they will remember at the moment it matters.",
    "Then hand it over and stop talking about it. A phone that gets a lecture every week becomes the thing they hide."])],
 widget=dict(kind="chooser", title="Which of the four are you giving first?",
   note="Pick the one you are actually ready for. Each has a different rule attached.",
   data=dict(empty="Pick a grant to see the rule that goes with it.", options=[
     dict(n="1", t="A device only", head="Calls and texts, nothing else",
       body=["This solves the original problem - reaching them - and almost nothing else changes. A basic handset or a smartwatch does it.",
             "The rule that goes with it: it charges in the kitchen. Set it now, while nobody minds, because you will want it in place before grant three."]),
     dict(n="2", t="A device and a number", head="Now other people can reach them",
       body=["The change here is direction. Up to now you were reaching them; now anybody with the number reaches them, at any hour.",
             "The rule: you both know who has the number. Not surveillance - just the same thing you would know about a landline in 1994."]),
     dict(n="3", t="Plus the open internet", head="This is the one people mean",
       body=["A browser is everything, including the things you would not install deliberately. Content filters help and are not a plan; assume they will see something they should not.",
             "The rule: tell me and nothing bad happens to you. Say that sentence out loud, in advance, and mean it. It is the only thing that keeps the channel open."]),
     dict(n="4", t="Plus the app store", head="Give this one last, and slowest",
       body=["This is the ability to install a new social world overnight without mentioning it. It is a different decision from the phone, and it deserves its own conversation - see Issue No. 03.",
             "The rule: three apps to start, chosen together, each one explained. Add more on a date, not on a mood."])])),
 kid=dict(scared="You disappearing into it.", say="Can we start with one that just calls and texts?",
   dont="&ldquo;Everyone has one.&rdquo; They know. It has never once worked.",
   job="Put it in the kitchen at night before they ask you to.",
   notyet="Ask what you&rsquo;d have to show them. Then show them, for a month.",
   why=["Here&rsquo;s the thing your grown-up is actually picturing: you, at midnight, awake, on a screen. Not you being irresponsible. Just you not sleeping.",
        "So the fastest way to a yes is to take that picture away before they mention it. If the phone lives in the kitchen at night, most of what they&rsquo;re worried about is already solved, and you didn&rsquo;t even have to argue."],
   steps=["Ask for the small version first - calls and texts. It is much easier to say yes to.",
          "Say where it will sleep, before they ask. Kitchen. Every night.",
          "Ask when you can talk about apps. Get an actual date and then don&rsquo;t bring it up until then."],
   widget=dict(kind="streak", title="Seven nights", note="If you already have any device - a tablet, a console, an old phone - park it outside your room at night. Seven nights. Say nothing.",
     data=dict(days=7, key="phone", unit="Night", empty="Tap a circle each night you park it outside your room.",
       verdicts=[dict(min=7, say="Seven nights. Now you can say &lsquo;I&rsquo;ve been doing this for a week&rsquo; and it&rsquo;s just true."),
                 dict(min=4, say="Over halfway. Still don&rsquo;t mention it - let them notice."),
                 dict(min=1, say="Started. The trick is doing it on the night you really don&rsquo;t want to.")])))),

dict(no="03", slug="being-online", title="Being online", ask="So you want to be online",
 ages=(12,15), band="Usually 12&ndash;15", colour="blue",
 thesis="This is not a screen-time decision, it is an <b>audience</b> decision. You are deciding whether your child gets a public - a room of people they cannot see, which keeps a copy of everything.",
 deciding=dict(q="Not <em>how long are they on it</em>. It is: who can see them, who can message them, and what happens to it afterwards?",
   bullets=["Public account or private","Who is allowed to send them a message","Whether you are in the audience"]),
 facts=["Thirteen is the platforms&rsquo; own minimum, and it is a legal floor rather than a recommendation of readiness. Nobody at those companies has met your child.",
        "Private-by-default costs nothing on day one and is a humiliation to impose in month six. This is the same shape as the phone-in-the-bedroom rule, and it is the same mistake."],
 scripts=[dict(role="Say", say="One condition. I get to see it. Not to police you - because you are thirteen, and I am not sending you into a room full of adults without knowing what the room is like.",
               why="Names the reason as protection rather than distrust, which is both kinder and true."),
          dict(role="The sentence that keeps the channel open", say="If something happens on there that upsets you, you can tell me and I will not take the account away.",
               why="Most children do not report because they expect the thing they love to be confiscated. Remove that fear and you get told things.")],
 dont=dict(say="Give me your phone. Now.",
   why="A surprise inspection buys one afternoon of information and costs every future disclosure. Visibility agreed in advance costs nothing and lasts."),
 rule=dict(text="The first account is private, and you are in the audience. Renegotiate on a named date, not on a good mood.",
   why="You are not trying to read their messages. You are trying to know the size and shape of the room."),
 ready=[dict(t="They can tell you what they would do if a stranger messaged them", why="Ask. Do not assume. The answer is usually thinner than you hope."),
        dict(t="They have told you about something upsetting online before you found it", why="This is the single best predictor you have."),
        dict(t="They understand that deleting is not undoing", why="Screenshots exist. Ask them to explain it back to you."),
        dict(t="You have agreed what happens if something goes wrong", why="Specifically: that the account does not get confiscated for reporting.")],
 notyet="A group chat with people you both know, first. Same skills, knowable room, and you find out how they behave in a group before the group is strangers.",
 depth=[("The three things that actually go wrong",
   ["<strong>Contact</strong> from people who should not be in touch. Private accounts and closed DMs handle most of it.",
    "<strong>Content</strong> they were not ready for. Filters reduce this; nothing eliminates it. Plan for the conversation afterwards rather than the wall beforehand.",
    "<strong>Comparison</strong>, which is the quiet one, and the one no setting fixes. It shows up as mood rather than as an incident, and you will notice it before they name it."]),
  ("What 'I get to see it' should actually mean",
   ["Not reading their messages. Following the account, knowing the handle, and being able to look at the public half without an argument.",
    "Agree the terms out loud: what you will look at, what you will not, and what would make you look closer. A teenager can live with a boundary they helped draw. They cannot live with an unpredictable one."])],
 widget=dict(kind="chooser", title="What are you actually worried about?",
   note="They need different answers. Picking the wrong one wastes the conversation.",
   data=dict(empty="Pick the one that keeps you up.", options=[
     dict(n="1", t="Strangers", head="Contact - the most fixable one",
       body=["This is largely a settings problem, and settings solve it well. Private account, DMs closed or restricted to people they follow, location off, no school name in the bio.",
             "Do it together, at the setup, in ten minutes. Then say the sentence that matters: if someone you do not know messages you, show me and nothing happens to you."]),
     dict(n="2", t="It never goes away", head="Permanence - a comprehension problem",
       body=["They know the words. They have not felt it. The useful move is concrete: ask what they would do if something they posted today were read out in a job interview in nine years.",
             "Not as a threat - as a genuine question. Most teenagers reason about this well when it is asked as a puzzle rather than a warning."]),
     dict(n="3", t="How much time it eats", head="Attention - the one you can model",
       body=["Rules here work badly and modelling works well. A house where adults put phones away at dinner has a different argument about screen time than one where they do not.",
             "If you want a rule, make it a place rather than a number: no phones at the table, none in bedrooms overnight. Places are enforceable. Minutes are not."]),
     dict(n="4", t="What it does to how they feel", head="Comparison - the hard one",
       body=["No setting touches this. What helps is naming the mechanism early: that they are comparing their ordinary Tuesday to other people&rsquo;s edited highlights, and that everyone is doing the same thing back at them.",
             "Then watch mood rather than minutes. If they come off it flatter than they went on, that is the signal - and it is worth saying out loud, gently, without making it a case for confiscation."])])),
 kid=dict(scared="Strangers, and stuff that never goes away.",
   say="You can follow my account. I&rsquo;d rather you saw it than found it.",
   dont="&ldquo;You don&rsquo;t get it.&rdquo; Maybe not. Doesn&rsquo;t help you.",
   job="Tell them one thing that happened online before they hear it from someone else.",
   notyet="Ask for a group chat with people you both know.",
   why=["Offering to be followed sounds like giving something up. It isn&rsquo;t. It&rsquo;s the fastest way to get an account at all, and after about two weeks they stop looking.",
        "The other one is harder and worth more. If something weird happens online and you tell them first, you become a person who reports things. That&rsquo;s worth a lot of freedom later."],
   steps=["Set it private together, on the first day. It&rsquo;s much easier than going private later.",
          "Ask them straight out: what would make you take this away? Then you know where the edges are.",
          "Tell them one small thing that happened online this week. Boring is fine. Doing it is the point."],
   widget=dict(kind="checklist", title="Before you ask, can you answer these?",
     note="If you can answer all five, you&rsquo;re making a much stronger case than most people your age.",
     data=dict(empty="Tick the ones you could actually answer right now.",
       items=[dict(t="What I&rsquo;d do if someone I don&rsquo;t know messages me"),
              dict(t="Why private is better than public to start with"),
              dict(t="What I&rsquo;d do if a friend posted something about me I hated"),
              dict(t="Who is allowed to know my school name"),
              dict(t="What I&rsquo;d do if I saw something that upset me")],
       verdicts=[dict(min=5, say="All five. Go and ask - and offer the answers before they ask the questions."),
                 dict(min=3, say="Good. Work out the missing ones first; they&rsquo;re the ones you&rsquo;ll get asked."),
                 dict(min=1, say="Start here. These are exactly the questions coming your way.")])))),
dict(no="04", slug="a-sleepover", title="A sleepover", ask="So you want a sleepover",
 ages=(6,10), band="Usually 6&ndash;10", colour="yellow",
 thesis="The question is almost never whether your child is ready. It is whether <b>you know the house</b> - and whether your kid has a working exit at one in the morning that does not cost them any dignity.",
 deciding=dict(q="Not <em>are they old enough</em>. It is: do I know this home, and does my child have a way out they will actually use?",
   bullets=["Whose house, and which adults are there overnight","Who else is staying","What the pickup plan is, exactly"]),
 facts=["The failure mode is not drama. It is a quiet child at 1am who has decided that asking to go home would be embarrassing, and who then says nothing for five hours.",
        "A child will use an escape hatch they are certain costs them nothing. They will not use one they have to argue for at midnight, in someone else&rsquo;s kitchen, in front of a friend."],
 scripts=[dict(role="Say", say="Two things and then yes. I am going to ring their mum and ask a few boring questions. And you can come home at any hour, no embarrassment, no questions until the morning. That is not failing. That is the deal.",
               why="Puts the exit in place before it is needed, and frames the call as routine rather than as suspicion of that family."),
          dict(role="On the doorstep, quietly", say="Text me the word and I will just come. You do not have to explain anything to anyone.",
               why="The code word exists so they never have to say the sentence out loud in front of their friend.")],
 dont=dict(say="You&rsquo;ll be fine!",
   why="It sounds kind and it quietly forecloses the one sentence you most need them to be able to say, which is <em>I am not fine</em>."),
 rule=dict(text="A code word, and a no-questions pickup. One text, you drive, nobody discusses it until morning.",
   why="Make the exit free and they will use it early. Make it cost something and they will endure the whole night instead."),
 ready=[dict(t="They can phone you themselves, and have", why="Not a text from someone else&rsquo;s parent. Their own voice, your number."),
        dict(t="They have done a late evening at that house and come home at nine", why="The ladder before the leap."),
        dict(t="They have said &lsquo;I don&rsquo;t like this&rsquo; to an adult who is not you", why="This is the actual skill being tested."),
        dict(t="You have had the boring-questions call", why="See the checklist. It takes four minutes.")],
 notyet="A late-over. All of the party, collected at nine, and nobody has to be brave about it. Most children who are not ready for the night are entirely ready for the evening.",
 depth=[("The boring questions, and how to ask them",
   ["Ring rather than text, keep it light, and ask them the way you would ask about a swimming pool - because that is exactly what they are: ordinary safety questions that most parents ask each other and nobody minds.",
    "If any answer is evasive, that is information. You are allowed to say &lsquo;I think we will do a late-over this time&rsquo; without giving a reason."]),
  ("If it goes wrong at 1am",
   ["Go. Do not negotiate on the phone, do not ask what happened, do not suggest they try to sleep. Drive.",
    "In the morning, ask once, gently, and accept a short answer. A child who is collected without fuss will do a sleepover again in a month. A child who is talked out of leaving may not do one for a year."])],
 widget=dict(kind="checklist", title="The four-minute phone call",
   note="Ask all six. Tick as you go. Most parents ask these and nobody minds being asked.",
   data=dict(empty="Tick them off during the call.",
     items=[dict(t="Who is home overnight?", why="Not who is home at bedtime. Overnight."),
            dict(t="Who else is staying?", why="Older siblings and their friends change the room."),
            dict(t="Where is everyone sleeping?", why="A plain question with a plain answer."),
            dict(t="What are the screen and film rules?", why="The most common cause of a distressed 1am call."),
            dict(t="Are there guns in the house, and how are they stored?", why="Ask it the way you would ask about a pool. In many countries this is the single highest-value question on the list; in others it is simply not relevant - use your judgement."),
            dict(t="Can I give you my number for anything at all?", why="Ends the call warmly and makes the exit two-way.")],
     verdicts=[dict(min=6, say="All six asked. Say yes and enjoy the quiet evening."),
               dict(min=4, say="Nearly. The unasked ones are usually the ones worth asking."),
               dict(min=1, say="Keep going - the whole call is about four minutes.")])),
 kid=dict(scared="You at 1am, in a house they&rsquo;ve never been in.",
   say="If I want to come home I&rsquo;ll text you. I won&rsquo;t be embarrassed.",
   dont="&ldquo;I&rsquo;ll be fine!&rdquo; Then at 1am you&rsquo;re stuck being fine.",
   job="Pick a code word together. Boring. Works.",
   notyet="Ask for a late-over. All the fun, home at nine.",
   why=["Here&rsquo;s a thing almost nobody tells you: loads of people want to go home at 1am on their first sleepover. It is completely normal and it is not being a baby.",
        "The reason it goes badly is that people decide it would be embarrassing to say so, and then lie awake until six. A code word fixes that. You text one word, they come, nobody says anything about it."],
   steps=["Agree the code word before you go. Any word. &lsquo;Bananas&rsquo; works.",
          "Take your own toothbrush and something that smells like home. Sounds childish; helps at 1am.",
          "If you want to go home, send the word. That&rsquo;s it. You never have to say it out loud to anyone."],
   widget=dict(kind="chooser", title="It&rsquo;s 1am and you&rsquo;re awake. Now what?",
     note="Pick what&rsquo;s actually happening.",
     data=dict(empty="Pick the one that&rsquo;s true.", options=[
       dict(n="1", t="I miss home", head="Very normal. Two options.",
         body=["Try one thing first: get a drink of water and lie back down. Sometimes that&rsquo;s genuinely it.",
               "If it&rsquo;s still there in twenty minutes, send the word. Going home at 1am is not failing at sleepovers. It&rsquo;s how most people learn to do them."]),
       dict(n="2", t="I just can&rsquo;t sleep", head="That happens to everyone",
         body=["A strange room is loud and the wrong temperature and smells wrong. You are not doing it badly.",
               "You don&rsquo;t have to sleep. You just have to rest. Lie still, let the night pass, and go home tired in the morning like everybody else."]),
       dict(n="3", t="Something happened that I didn&rsquo;t like", head="Send the word. Now.",
         body=["You do not need to explain it, be sure about it, or be able to describe it. Not liking it is enough.",
               "Text the word. Your grown-up will come and won&rsquo;t ask anything until the morning - and you can tell them as much or as little as you want then."]),
       dict(n="4", t="I feel ill", head="Wake an adult in the house",
         body=["Don&rsquo;t lie there hoping it passes. Wake whoever&rsquo;s in charge - that&rsquo;s genuinely what they&rsquo;re there for, and they will not mind.",
               "Then text your grown-up too. Two adults knowing is better than nobody knowing."])])))),

dict(no="05", slug="going-somewhere-alone", title="Going somewhere alone", ask="So you want to go on your own",
 ages=(8,12), band="Usually 8&ndash;12", colour="green",
 thesis="Independence is not a switch you flip at an age. It is a <b>distance</b>, and you extend it. The question is never the world in general - it is this route, at this hour, with this child.",
 deciding=dict(q="Not <em>is the world safe</em>. It is: does my kid have the judgement for this specific journey, and do they know what to do when it goes wrong?",
   bullets=["Which route, at what time","What happens when plan A fails","How they tell you they arrived"]),
 facts=["The risk on a walk to school is overwhelmingly traffic, not strangers. Rehearse the road, not the fear.",
        "A long warning about strangers reliably raises anxiety without raising a single skill. Twenty minutes practising the worst junction does the opposite."],
 scripts=[dict(role="Say", say="We are going to walk it together three times. Then you walk it while I wait at the other end. Then you do it on your own. And before any of that - tell me what you would do if the shop is shut.",
               why="A ladder with a named top rung, and a failure question rather than a fear lecture."),
          dict(role="Instead of the stranger talk", say="If you ever need help and I am not there, ask a woman with children, or someone working in a shop.",
               why="Actionable. &lsquo;Don&rsquo;t talk to strangers&rsquo; leaves a lost child with no one to ask.")],
 dont=dict(say="Nothing is going to happen.",
   why="It is a promise you cannot keep, and it teaches them that surprises are outside the plan rather than part of it. Then the first surprise feels like catastrophe."),
 rule=dict(text="Name the failure plan out loud before the first solo trip. Shop shut, friend not there, phone dead, feels wrong.",
   why="Confidence comes from having somewhere to go when the plan breaks - not from being told it will not break."),
 ready=[dict(t="They cross the worst road correctly without being reminded", why="Watch them do it while you say nothing. That is the test."),
        dict(t="They know an address and a phone number by heart", why="Not in the phone. In their head, for when the phone is dead."),
        dict(t="They have solved one small problem alone and told you about it", why="Evidence of judgement, not just obedience."),
        dict(t="You have walked the route together at least three times", why="Including once in the rain, and once at the actual time of day.")],
 notyet="Shorten the leg. Half the route, or the same route at a busier hour, is a genuine yes rather than a soft no - and it is the next rung, not a consolation prize.",
 depth=[("Build the ladder, not the leap",
   ["Together, three times, at the real time of day. Then they walk while you wait at the far end. Then they walk and you are at home. Then a different route.",
    "Each rung is small enough to be boring, which is exactly why it works. Nobody's judgement improves by being thrown into the deep end; it improves by being right about small things repeatedly."]),
  ("What to give them, and what not to",
   ["Give them: the route, the failure plan, a memorised phone number, and a way to say they have arrived.",
    "Do not give them: a running commentary of everything that could go wrong. A child who has been frightened into independence is not independent, they are just alone and scared."])],
 widget=dict(kind="dial", title="How many practice runs have you actually done?",
   note="Together, on the real route, at the real time.",
   data=dict(label="Practice runs completed", min=0, max=6, value=0, suffix=" runs",
     bands=[dict(upto=0, say="None yet. Do the first one this week - walk it together and let them lead, while you say nothing at junctions."),
            dict(upto=1, say="One. Do the next one at the actual time of day they would travel. Traffic at 8:15am is a different route from traffic at 2pm."),
            dict(upto=2, say="Two. On the third, hand over the decisions: let them choose when to cross while you stay quiet and watch what they do."),
            dict(upto=3, say="Three together. Time for the next rung - they walk it, you wait at the far end. Do not follow at a distance; they will spot you and it teaches nothing."),
            dict(upto=4, say="They have done it with you at the far end. Next: they go, you stay home, and they message on arrival."),
            dict(upto=6, say="That is the ladder. If the failure plan has been said out loud, this is a yes - and it should be announced as one, warmly, rather than allowed to happen by default.")])),
 kid=dict(scared="Roads. Honestly, mostly roads.",
   say="Can we walk it together three times first?",
   dont="&ldquo;Nothing&rsquo;s going to happen.&rdquo; You can&rsquo;t promise that, so don&rsquo;t.",
   job="Say out loud what you&rsquo;d do if the shop&rsquo;s shut and your phone&rsquo;s dead. Before they ask.",
   notyet="Ask for half the route.",
   why=["Grown-ups look worried about this one because of films. Actually the thing they&rsquo;re right to worry about is traffic, which is boring and fixable.",
        "So show them you&rsquo;re good at roads, not that you&rsquo;re brave. Being brave is not the thing being tested here."],
   steps=["Ask to walk it together three times, and you do the deciding at the crossings.",
          "Learn one phone number off by heart. Not in your phone - in your head.",
          "Tell them your plan for three things going wrong. Shop shut. Friend not there. Phone dead."],
   widget=dict(kind="checklist", title="Could you answer these right now?",
     note="These are the exact things they&rsquo;re about to ask you.",
     data=dict(empty="Tick the ones you could answer without thinking.",
       items=[dict(t="A phone number I know by heart"),
              dict(t="My address, out loud, correctly"),
              dict(t="What I do if the shop is shut"),
              dict(t="What I do if my phone dies"),
              dict(t="Who I&rsquo;d ask for help if I needed it", why="Someone working in a shop, or a woman with kids, is a good answer."),
              dict(t="What I do if something just feels wrong", why="Go into a shop. That&rsquo;s always a fine answer.")],
       verdicts=[dict(min=6, say="All six. Tell them the answers before they ask the questions - it&rsquo;s a very strong move."),
                 dict(min=4, say="Close. Learn the missing ones today, they take about five minutes."),
                 dict(min=1, say="Good start. Get the phone number and address done first.")])))),
dict(no="06", slug="quitting", title="Quitting", ask="So you want to quit",
 ages=(7,16), band="Any age, repeatedly", colour="pink",
 thesis="The useful question is not whether to let them quit. It is whether they are quitting the activity or <b>quitting a bad week</b> - and those need opposite answers.",
 deciding=dict(q="Not <em>do we allow quitting</em>. It is: which part do they hate - the thing, the person, the practising, or the level? Four different problems, four different fixes.",
   bullets=["Quit, change teacher or team, or change the amount","When the exit happens","What they owe the other people involved"]),
 facts=["The urge to quit usually peaks just before competence, not at the start. The plateau - where effort stops producing visible improvement - is the most common place a child asks to stop.",
        "&lsquo;We don&rsquo;t quit things&rsquo; teaches that stopping anything is a defect of character. It is the belief that keeps a twenty-six-year-old in a job they hate."],
 scripts=[dict(role="Say", say="You can quit. Not today - at the end of term, so you are leaving from a decision instead of a bad Tuesday. And I want to know which part you hate, because if it is the teacher we have a much easier problem.",
               why="Grants the thing, sets a boundary, and starts the diagnosis in one move."),
          dict(role="Three weeks later", say="Still want to stop? Then we stop, and I am not going to make you feel bad about it.",
               why="Keeping this promise is the whole exercise. If you renege here, they will not tell you the truth next time.")],
 dont=dict(say="We don&rsquo;t quit things in this family.",
   why="It does not produce persistence. It produces children who conceal that they are miserable, because misery has been defined as a character flaw."),
 rule=dict(text="Quit at a boundary, not in a bad moment - and finish what other people are counting on.",
   why="The lesson worth keeping is not persistence for its own sake. It is that you exit cleanly and you do not leave a team short."),
 ready=[dict(t="They can name the specific part they hate", why="&lsquo;I hate it&rsquo; is a mood. &lsquo;I hate the Saturday matches&rsquo; is a fact you can work with."),
        dict(t="They have tried one change", why="Different teacher, different level, less of it. One change first."),
        dict(t="They have said it calmly, more than once, across several weeks", why="Once, in tears, after a bad session, is not data."),
        dict(t="Nobody else is depending on them this season", why="If they are, the exit is at the end of it.")],
 notyet="Three more weeks with exactly one thing changed, and a promise you will honour whatever they say at the end of it. Then honour it - that is the part that counts.",
 depth=[("Diagnose before you decide",
   ["Children almost never say &lsquo;the teacher humiliates me in front of the group&rsquo;. They say &lsquo;I hate piano&rsquo;. The sentence you get is a summary, and the summary is usually wrong.",
    "So ask about the parts. When in the week do you dread it? What is the worst bit - going, being there, or the practising at home? Is there anyone there you like? The answers sort the problem quickly."]),
  ("Quitting well is a skill worth teaching",
   ["Tell the teacher or coach themselves, in person or on the phone. Thank them. Finish the commitment. Return the kit.",
    "A child who has quit one thing well is far better equipped than one who has never been allowed to stop anything - because at some point they will need to leave a job, a course, or a relationship, and this is the rehearsal."])],
 widget=dict(kind="chooser", title="Which part do they actually hate?",
   note="Ask them, then pick. The four have genuinely different answers.",
   data=dict(empty="Pick the part they named.", options=[
     dict(n="1", t="The thing itself", head="This is the real one",
       body=["If they dislike the activity itself - not the people, not the practice - that is a legitimate preference and it is allowed.",
             "Let them finish the commitment and stop. Then ask what they would like to try instead, and take that answer seriously. Quitting into nothing feels like failure; quitting into something else feels like a choice."]),
     dict(n="2", t="The teacher or coach", head="Easiest problem you will ever have",
       body=["This is the most common answer and the most commonly missed one, because children rarely volunteer it - especially if the adult is well-liked by everyone else.",
             "Change the teacher, the class, or the club. Do not make them justify it. A different adult frequently produces a child who loves the thing they were begging to quit."]),
     dict(n="3", t="The practising", head="Reduce it before you end it",
       body=["Daily practice is where most instruments die. Ten focused minutes beats forty resentful ones, and dropping to that is not the same as giving up.",
             "Try one term at half the practice and no exams. If they still want out at the end of it, you have your answer and it is a real one."]),
     dict(n="4", t="It is too hard now", head="The plateau - hold if you can",
       body=["This is the moment just before it gets good, and it is the single most common place people quit anything. Worth naming out loud: this bit is horrible for everyone and it does end.",
             "Offer a smaller version rather than a heroic push - drop a grade, drop a team, keep going. If they still want out in three weeks, let them go without a speech."])])),
 kid=dict(scared="That you&rsquo;ll quit everything from now on.",
   say="I want to stop at the end of term. Not today.",
   dont="&ldquo;I hate it.&rdquo; That&rsquo;s a noise, not information.",
   job="Work out which bit you hate: the thing, the person, the practising, or that it got hard.",
   notyet="Ask to change one thing and try three more weeks.",
   why=["Saying &lsquo;I want to quit&rsquo; on a bad day almost never works, because they can tell it&rsquo;s the day talking. Saying it calmly, twice, three weeks apart, works much better.",
        "And here&rsquo;s the useful bit: if what you actually hate is the coach, or the practising, that&rsquo;s a much smaller problem and you can probably keep the good parts."],
   steps=["Work out which of the four bits you hate. Be honest with yourself first.",
          "Ask to stop at the end of term, not today. It makes you sound like someone deciding, not sulking.",
          "Offer to try one change first - different class, less practice. It usually gets you a yes either way."],
   widget=dict(kind="chooser", title="Which bit do you actually hate?",
     note="Be honest. It changes what you should ask for.",
     data=dict(empty="Pick the truest one.", options=[
       dict(n="1", t="The whole thing", head="Then say so, calmly",
         body=["That&rsquo;s allowed. People are allowed to not like things.",
               "Ask to stop at the end of term and offer to tell the coach yourself. Doing that makes grown-ups take you seriously more than almost anything else."]),
       dict(n="2", t="The coach or teacher", head="Say this bit out loud",
         body=["This is really common and hardly anyone mentions it, especially if everyone else likes them.",
               "You don&rsquo;t have to explain why. &lsquo;I don&rsquo;t like how they talk to me&rsquo; is enough. Ask to switch rather than stop - you might find you like the thing after all."]),
       dict(n="3", t="Practising at home", head="Ask for less, not none",
         body=["Try asking for ten minutes a day instead of whatever it is now. Ten real minutes is better than forty miserable ones anyway.",
               "This is an easy yes for most grown-ups, and it often fixes the whole problem."]),
       dict(n="4", t="It got too hard", head="This bit is horrible for everyone",
         body=["The point where it stops getting easier is where nearly everybody quits everything. It is not a sign you&rsquo;re bad at it. It&rsquo;s the normal middle.",
               "Ask to drop down a level for a bit instead of stopping. If you still hate it in three weeks, then ask to stop - and you&rsquo;ll know it wasn&rsquo;t just the hard bit."])])))),

dict(no="07", slug="staying-home-alone", title="Staying home alone", ask="So you want to stay home alone",
 ages=(9,13), band="Usually 9&ndash;13", colour="blue",
 thesis="You are not really assessing whether they can be trusted alone. You are assessing <b>what they do when something goes wrong</b> - and the things that go wrong are far more boring than the ones you are picturing.",
 deciding=dict(q="Not <em>are they mature enough</em>. It is: do they know what to do about the doorbell, the alarm, the locked door, and not being able to reach me?",
   bullets=["How long, and how often","Whether a sibling is company or a second job","What is off limits - oven, bath, front door"]),
 facts=["First-time-alone problems are almost always mundane: a delivery, a locked door, burnt toast setting off the alarm, a sibling fight. Rehearse those four and you have covered most of it.",
        "Leaving a much younger sibling in their care is a different decision from leaving them alone, and it is usually a later one. Being responsible for yourself and being responsible for a five-year-old are not the same job."],
 scripts=[dict(role="Say", say="Twenty minutes while I get milk. Before I go: tell me what you do if someone knocks, if you get locked out, and if you ring me and I do not pick up.",
               why="Short, specific, and rehearsed out loud rather than assumed."),
          dict(role="When you get back", say="How was it? Anything happen? Right - next time I will be gone about an hour.",
               why="Names the ladder. They should know the next rung exists.")],
 dont=dict(say="Just don&rsquo;t open the door to anyone.",
   why="One prohibition and no plan. They need a script for the four boring emergencies, not a single rule that leaves them frozen when the smoke alarm goes off."),
 rule=dict(text="Start at twenty minutes, and come back exactly when you said you would.",
   why="The first reliability being tested here is yours. A parent who is an hour late teaches the house that stated times are approximate - and that is the lesson that comes back at sixteen."),
 ready=[dict(t="They can be alone and bored without ringing you five times", why="Boredom tolerance is the actual prerequisite."),
        dict(t="They follow a rule you are not there to enforce", why="You will know whether this is true."),
        dict(t="They can call an adult who is not you", why="A neighbour, a grandparent. Someone reachable when you are not."),
        dict(t="They know what to do about the door, the alarm and the keys", why="Rehearsed out loud, not assumed.")],
 notyet="Alone in the house while you are in the garden. Then while you walk to the end of the street. The ladder here is measured in minutes, and it climbs quickly.",
 depth=[("Rehearse the four boring emergencies",
   ["<strong>The door.</strong> Agreed answer: do not open it. Deliveries can be left. If someone will not go away, ring me.",
    "<strong>The alarm.</strong> If it is toast, open a window. If there is any actual smoke, out of the house first and ring from outside - do not investigate.",
    "<strong>Locked out.</strong> A named neighbour, or a spot to wait that is not the doorstep. Decide it now.",
    "<strong>Cannot reach you.</strong> A second adult by name, and the reassurance that this is normal - phones die and signal drops, and it does not mean anything has happened to you."]),
  ("The sibling question",
   ["Two children alone is not half the risk, it is a different one: the risk is now a fight rather than an accident. Agree in advance who is in charge of what, and be explicit that being older does not mean being the boss of everything.",
    "If one child is much younger, that is babysitting, and it deserves its own conversation, its own rules, and - once they are old enough for it to be a real job - probably its own pay."])],
 widget=dict(kind="dial", title="How long, realistically?",
   note="Each duration needs a different amount of preparation.",
   data=dict(label="Minutes alone", min=10, max=240, value=20, step=10, suffix=" min",
     bands=[dict(upto=20, say="The right first rung. Local, phone on, back exactly on time. This is about proving <em>your</em> reliability as much as theirs."),
            dict(upto=45, say="Long enough to be bored. Make sure they have something to do that is not a screen, and that they know the door rule."),
            dict(upto=90, say="Now they will probably need food. Agree what they are allowed to use - toaster yes, hob no, is a common line - and where the snacks are."),
            dict(upto=150, say="Long enough that something might actually happen. A named backup adult who is nearby, not just reachable, should exist before you do this."),
            dict(upto=240, say="Half a day. This wants a proper plan: meals, the backup adult, what happens if you are delayed, and a clear rule about whether anyone else is allowed in the house.")])),
 kid=dict(scared="The doorbell. And you not picking up.",
   say="Give me twenty minutes while you get milk.",
   dont="&ldquo;I&rsquo;m not a baby.&rdquo; True. Still annoying.",
   job="Answer your phone. Every time. Miss it once and this gets very slow.",
   notyet="Ask for ten minutes while they&rsquo;re in the garden.",
   why=["They&rsquo;re not picturing burglars. They&rsquo;re picturing you not answering your phone and them driving home imagining things.",
        "So the whole job is: be reachable and be boring. Ask for twenty minutes, not an afternoon. Small and successful beats big and refused."],
   steps=["Ask for twenty minutes while they do something local. Not a whole afternoon.",
          "Tell them your plan for the door, the smoke alarm, and getting locked out - before they ask you.",
          "Answer your phone every single time. This is the entire test and it is easy to pass."],
   widget=dict(kind="checklist", title="Do you know what you&rsquo;d do?",
     note="These four are what actually happens. Not burglars.",
     data=dict(empty="Tick the ones you&rsquo;ve got an answer for.",
       items=[dict(t="Someone knocks at the door", why="Don&rsquo;t open it. Deliveries can be left."),
              dict(t="The smoke alarm goes off because of toast", why="Open a window. If there&rsquo;s real smoke, go outside first, then ring."),
              dict(t="You get locked out", why="Have a named neighbour or a place to wait. Decide it now, not then."),
              dict(t="You ring them and they don&rsquo;t pick up", why="Ring the backup adult. Phones die. It doesn&rsquo;t mean anything bad."),
              dict(t="You know a second adult&rsquo;s number", why="Not just in your phone.")],
       verdicts=[dict(min=5, say="All five. Say these out loud to them before they ask - that&rsquo;s what gets you a yes."),
                 dict(min=3, say="Nearly. Sort the missing ones out and then go and ask."),
                 dict(min=1, say="Work through the rest with your grown-up. It takes about ten minutes.")])))),
dict(no="08", slug="money-of-their-own", title="Money of their own", ask="So you want your own money",
 ages=(7,14), band="Usually 7&ndash;14", colour="yellow",
 thesis="The decision is not how much. It is whether you are giving them money, or giving them <b>the right to make a bad purchase</b> - because only the second one teaches anything.",
 deciding=dict(q="Not <em>what is the right amount</em>. It is: am I actually going to let them lose it?",
   bullets=["The amount, and how often","Whether it is tied to chores","Whether you keep a veto"]),
 facts=["Money only teaches when it can be lost. An allowance that gets topped up after a bad decision is a lesson that has been deleted, at full price.",
        "Pricing every household job creates a market where there was a family. Once the bins have a rate, carrying your own plate becomes negotiable."],
 scripts=[dict(role="Say", say="It is yours. I will tell you once if I think something is a bad idea, and then I will stop. And I am not going to replace it. That is the whole point of it being yours.",
               why="States the deal and pre-commits you to the hard part, in front of a witness."),
          dict(role="After the inevitable bad purchase", say="Yeah. That is a rubbish one, isn&rsquo;t it. What will you do differently with the next lot?",
               why="No lecture, no rescue, no I-told-you-so. The disappointment is doing the teaching; do not interrupt it.")],
 dont=dict(say="Everything is paid, per chore.",
   why="It prices things that should be free, and you will eventually find yourself negotiating a fee with a child for tidying their own room."),
 rule=dict(text="Let them buy the rubbish thing.",
   why="A twenty-pound regret at nine is the cheapest financial education available anywhere, and it does not go on a credit record."),
 ready=[dict(t="They can wait a week for something they want", why="If not, start with a smaller amount more often."),
        dict(t="They can tell you roughly what things cost", why="Ask what they think a loaf of bread costs. The answers are educational."),
        dict(t="They have saved for one thing all the way to the end", why="The completed save is the skill. The item is incidental."),
        dict(t="You are genuinely prepared not to bail them out", why="Be honest. If you will cave, give less, so the lesson is affordable.")],
 notyet="A smaller amount, weekly, in cash, where they can physically watch it leave. Cash is a better teacher than a card at this age precisely because it visibly runs out.",
 depth=[("Tie it to chores, or not?",
   ["The tidy answer: some jobs are family membership and are unpaid - your own plate, your own room, your own washing. Extra jobs beyond that can be paid, at a rate agreed in advance.",
    "That split gives you the lesson of earning without turning the household into a marketplace. It also means the allowance itself can be unconditional, which matters, because an allowance you can withdraw is not really theirs and does not teach ownership."]),
  ("Saving, without making it joyless",
   ["Splitting money into spend, save and give sounds excellent and mostly fails, because the proportions get imposed. A simpler version works better: they spend what they like, and anything for something big goes in a visible jar or a named account.",
    "The visible part matters. A number in your banking app is abstract; a jar filling up is not. And when they finally buy the thing, be pleased about it - a save that ends in a lecture about whether it was worth it teaches them not to save."])],
 widget=dict(kind="dial", title="How much, at what age?",
   note="There is no correct number. This is a common range and what it tends to buy.",
   data=dict(label="Their age", min=6, max=16, value=9, suffix=" years old",
     bands=[dict(upto=7, say="Small and weekly, in coins - the equivalent of a couple of pounds or dollars. At this age the lesson is entirely that money runs out, and that is best learned in a shop, in cash."),
            dict(upto=9, say="Still weekly, still cash. Enough for a small toy after two weeks of saving - the first experience of waiting is the whole curriculum here."),
            dict(upto=11, say="Weekly or fortnightly, and now big enough to make a genuinely bad purchase. This is the age the bad purchase does the most good, so let it happen."),
            dict(upto=13, say="Consider monthly. It is a real step up in difficulty - running out in week two and waiting is a lesson that only monthly can teach."),
            dict(upto=16, say="Monthly, and now worth folding in some real costs they control - phone credit, some clothes, going out. A budget with actual obligations in it is the last rung before a first wage.")])),
 kid=dict(scared="Paying for the same thing twice.",
   say="If I buy something rubbish, don&rsquo;t replace it.",
   dont="&ldquo;Can I have it early?&rdquo; Not once. Ever.",
   job="Save for one thing all the way to the end, where they can watch you do it.",
   notyet="Ask for less, weekly, in cash.",
   why=["Saying &lsquo;don&rsquo;t replace it if I waste it&rsquo; sounds mad. It is actually the single most convincing sentence available to you, because it is exactly what they&rsquo;re worried about.",
        "And asking for an advance is the one thing that ends this fastest. Once you&rsquo;ve borrowed against next week, you are not someone with their own money - you&rsquo;re someone with a debt."],
   steps=["Ask for a small amount, weekly, in cash. Small gets a yes much faster than big.",
          "Say up front that you don&rsquo;t want rescuing if you waste it. Then don&rsquo;t ask to be rescued.",
          "Save for one thing, right to the end, without giving up halfway. One completed save changes what they think of you."],
   widget=dict(kind="streak", title="Ten weeks of saving something",
     note="Any amount. The point is not the total - it&rsquo;s that you didn&rsquo;t stop.",
     data=dict(days=10, key="save", unit="Week", empty="Tap one each week you put something away.",
       verdicts=[dict(min=10, say="Ten weeks straight. Hardly anyone does this. Go and tell them - this one you <em>are</em> allowed to mention."),
                 dict(min=6, say="Six weeks in. This is the bit where people give up, so keep going."),
                 dict(min=3, say="Three weeks. Put it somewhere you can see it filling up - it makes a surprising difference."),
                 dict(min=1, say="Started. Same day each week works best.")])))),

dict(no="09", slug="a-first-job", title="A first job", ask="So you want a job",
 ages=(13,17), band="Usually 13&ndash;17", colour="green",
 thesis="The money is the least interesting part. The real curriculum is <b>having a boss who is not a parent</b> - someone who corrects them, and whom they have to say no to.",
 deciding=dict(q="Not <em>do they need the money</em>. It is: whose time is it now, and what happens the first time work and school collide?",
   bullets=["An hours cap, agreed in writing","The school-night rule","What happens to the money"]),
 facts=["School performance generally holds up to somewhere around ten to fifteen hours a week and starts to slide beyond it. Agree the cap before the first shift, not after the first bad report.",
        "The most valuable hour of a first job is the one where they have to tell a manager they cannot work Saturday. Do not take that hour away from them by making the call yourself."],
 scripts=[dict(role="Say", say="Yes. The cap is twelve hours, nothing after nine on a school night, and we look at it again in a month. What you earn is yours - I would like some of it to go somewhere it can sit.",
               why="Specific, time-limited, and it hands over the money properly rather than conditionally."),
          dict(role="When the rota clashes with an exam", say="That is yours to sort out. What are you going to say to them?",
               why="Rehearse it with them if they want. Do not make the call.")],
 dont=dict(say="I&rsquo;ll ring your manager and sort the rota.",
   why="You have just removed the only part of the job that was going to teach them anything they could not learn from pocket money."),
 rule=dict(text="They make the phone calls. Including the awkward one where they cannot work Saturday.",
   why="Asking an unrelated adult for something, out loud, is the skill. Everything else is logistics."),
 ready=[dict(t="They can wake themselves up", why="With their own alarm, on a day they do not want to."),
        dict(t="They can be corrected without it ruining the day", why="A manager will be blunter than you are."),
        dict(t="They can turn down a shift without you in the room", why="Rehearse it once. Then step back."),
        dict(t="You have agreed the hours cap out loud", why="Before the first shift. It is unenforceable afterwards.")],
 notyet="One-off paid work first - babysitting, a neighbour&rsquo;s garden, a weekend of something. Same lesson, no rota, and it tells you a great deal about how they will handle the real thing.",
 depth=[("What the money is for",
   ["Resist assigning it. An allowance you control teaches budgeting; a wage you control teaches nothing, because it is not really theirs.",
    "One reasonable ask: some proportion goes somewhere it cannot be spent this week. Frame it as a suggestion with a reason, not a condition of the job, and let them choose the number."]),
  ("The first bad week",
   ["There will be a week where they are tired, behind, and regretting it. That is the week the whole thing is worth - and the temptation to say I told you so will be enormous.",
    "Do not. Ask what they want to change: fewer hours, different shifts, or out. Then let them execute it themselves. A teenager who negotiates their own hours down has learned something no lecture delivers."])],
 widget=dict(kind="dial", title="Hours a week, and what tends to happen",
   note="Rough bands from the research on term-time work. Your kid is not a statistic - but the shape is real.",
   data=dict(label="Hours per week during term", min=0, max=25, value=10, suffix=" hrs",
     bands=[dict(upto=4, say="Barely a job, and genuinely useful. A shift or two a week gets the boss, the wage and the responsibility with essentially no academic cost."),
            dict(upto=10, say="The sweet spot in most of the research. Enough to matter, small enough that school absorbs it. A sensible place to set the first cap."),
            dict(upto=15, say="The upper edge. Fine for many, but this is where sleep is usually the first thing to go - watch bedtimes rather than grades, because sleep moves first."),
            dict(upto=20, say="Beyond where most studies see grades start to slide. Workable in a light school year; risky in an exam year. Worth an explicit review date."),
            dict(upto=25, say="This is a part-time job with school attached. Occasionally the right call - if they have a specific goal and know the trade - but it should be a decision made out loud, not a rota that quietly grew.")])),
 kid=dict(scared="Your sleep.",
   say="Cap my hours, and check my grades in a month.",
   dont="&ldquo;It won&rsquo;t affect anything.&rdquo; It will. Say so first.",
   job="Make the phone calls yourself. Including the awkward one.",
   notyet="Ask to do one paid thing first. Babysitting. Someone&rsquo;s garden.",
   why=["Offering the cap yourself is the move here. If you say &lsquo;cap me at ten hours and check my grades in a month&rsquo;, you&rsquo;ve just made their argument for them and there&rsquo;s nothing left to refuse.",
        "The bit that will actually be hard is ringing a manager to say you can&rsquo;t work Saturday. Do it anyway. That phone call is the most useful thing about the whole job."],
   steps=["Suggest the hours cap before they do. Ten is a good number to offer.",
          "Offer a check-in after a month, with your actual grades. It sounds confident because it is.",
          "Make every work phone call yourself, even the awkward ones. Especially those."],
   widget=dict(kind="checklist", title="Can you do these yet?",
     note="Be honest - these are the job, more than the work is.",
     data=dict(empty="Tick what&rsquo;s already true.",
       items=[dict(t="I wake myself up with my own alarm", why="On a day you don&rsquo;t want to."),
              dict(t="I can be told I did something wrong without it wrecking my day"),
              dict(t="I can ring an adult I don&rsquo;t know and ask for something"),
              dict(t="I can say no to a shift", why="Out loud, to a manager, on the phone."),
              dict(t="I know what I&rsquo;d cut if my grades dropped")],
       verdicts=[dict(min=5, say="All five. You&rsquo;re more ready than most adults think you are - say these out loud when you ask."),
                 dict(min=3, say="Good. Practise the phone call one, it&rsquo;s the one that actually matters."),
                 dict(min=1, say="Start with the alarm. Two weeks of waking yourself up is a real argument.")])))),
dict(no="10", slug="how-they-look", title="How they look", ask="So you want to change how you look",
 ages=(10,16), band="Usually 10&ndash;16", colour="pink",
 thesis="Sort every request onto one axis and most of the argument disappears: <b>grows back, washes out, or does not.</b> Hair grows. Dye fades. Most holes close. Tattoos do not.",
 deciding=dict(q="Not <em>do I like it</em>. It is: is this reversible - and if it is, why am I in the conversation at all?",
   bullets=["Which column it falls in","Any school rule that genuinely exists","Who pays"]),
 facts=["Almost every fight in this category is about a reversible thing. Parents spend their authority on hair colour and have none left for the permanent list.",
        "You get a limited number of vetoes per teenager. Green hair is a poor place to spend one, and they will remember exactly which hill you chose."],
 scripts=[dict(role="Say", say="My rule is simple. If it grows back or washes out, it is your call. If it does not, we wait until you are sixteen - and then it is still your call.",
               why="A rule they can predict, apply themselves, and argue with on its merits rather than on your mood."),
          dict(role="When you hate it", say="Not what I would have picked. Your head though.",
               why="Say it warmly and then genuinely drop it. Withholding approval while granting permission is worse than refusing.")],
 dont=dict(say="What will your grandmother say?",
   why="It moves the decision from their body to other people&rsquo;s opinions, and turns a small aesthetic choice into a fight about control - which you will lose eventually anyway, on a worse day."),
 rule=dict(text="Reversible is theirs. Save your no for the permanent list.",
   why="It is a rule that is legible from the outside, which means it does not feel like arbitrary power - and that is what makes it survivable."),
 ready=[dict(t="It grows back or washes out", why="Then it is a yes. Say yes and move on."),
        dict(t="There is a real school rule, not an assumption", why="Check the actual policy. People invent these."),
        dict(t="They have wanted it for more than a fortnight", why="Useful for the permanent list only. Do not apply it to hair dye."),
        dict(t="You have agreed who pays for it, and for fixing it", why="Especially bleach. Bleach goes wrong.")],
 notyet="For permanent things: a date, not a lecture. And say plainly that the answer at that date is very likely yes - a &lsquo;not yet&rsquo; that is secretly a no is the thing that ends honest conversation.",
 depth=[("The sorting rule, in practice",
   ["Hair colour, length, style, makeup, nail varnish, most clothing: <strong>reversible</strong>. Default yes. The cost of a bad haircut is six weeks of a bad haircut, which is a lesson delivered free.",
    "Ear piercing: <strong>mostly reversible</strong>, closes over, common from young. Cartilage and body piercings are slower to heal and more prone to infection - a real reason for a real wait, and one that is worth explaining as such.",
    "Tattoos: <strong>not reversible</strong>, and almost everywhere illegal below eighteen anyway, which usefully makes it not your rule."]),
  ("What this is usually actually about",
   ["At this age appearance is how identity gets tested in public. The request is rarely about the hair; it is about being the author of something visible.",
    "Which is why granting the reversible ones cheaply is such a good trade. They get authorship, you keep your vetoes, and the whole category stops being a battleground - so that when something genuinely permanent comes up, you are a person whose no means something."])],
 widget=dict(kind="sorter", title="Sort the list before the argument",
   note="Put each one where it belongs. The point is how few land in the last column.",
   data=dict(done="Notice how few are permanent. That is the whole argument - and it is the one to have with yourself before you have it with them.",
     buckets=[dict(t="Grows back"), dict(t="Washes out"), dict(t="Permanent")],
     items=[dict(t="A very short haircut", bucket=0),
            dict(t="Blue hair dye", bucket=1),
            dict(t="Bleached hair", bucket=1),
            dict(t="Nail varnish", bucket=1),
            dict(t="Earlobe piercing", bucket=0),
            dict(t="Cartilage piercing", bucket=0),
            dict(t="Shaved eyebrow slit", bucket=0),
            dict(t="A tattoo", bucket=2)])),
 kid=dict(scared="Only the permanent ones. That&rsquo;s genuinely it.",
   say="This one washes out. Can that one be mine?",
   dont="&ldquo;It&rsquo;s my body.&rdquo; True. Still loses the argument.",
   job="Split your list into grows-back and doesn&rsquo;t. Ask for the grows-back ones first.",
   notyet="Get a date for the permanent one. Then drop it until then.",
   why=["Grown-ups mostly panic about this because they picture the permanent version. If you show them you already know the difference, you&rsquo;ve done most of the work.",
        "So lead with &lsquo;this washes out&rsquo;. It sounds like you&rsquo;ve thought about it, because you have, and it&rsquo;s very hard to argue with."],
   steps=["Sort your list yourself first: grows back, washes out, or permanent.",
          "Ask for the reversible ones. Say the word &lsquo;reversible&rsquo; - it does a lot of work.",
          "For a permanent one, ask for a date instead of a yes. Then genuinely don&rsquo;t mention it again until then."],
   widget=dict(kind="sorter", title="Which of yours grow back?",
     note="Sort them. Then ask for the first two columns.",
     data=dict(done="Everything in the first two columns is a reasonable thing to ask for right now. Start there.",
       buckets=[dict(t="Grows back"), dict(t="Washes out"), dict(t="Forever")],
       items=[dict(t="Cutting it all off", bucket=0),
              dict(t="Dyeing it blue", bucket=1),
              dict(t="Bleaching it", bucket=1),
              dict(t="Painted nails", bucket=1),
              dict(t="Ears pierced", bucket=0),
              dict(t="A tattoo", bucket=2)])))),

dict(no="11", slug="going-out-with-someone", title="Going out with someone", ask="So you want to go out with someone",
 ages=(13,17), band="Usually 13&ndash;17", colour="blue",
 thesis="This one arrives whether or not you decided anything. So the real decision is not permission. It is whether they will <b>tell you anything</b> once it has started.",
 deciding=dict(q="Not <em>should I allow this</em>. It is: am I someone they can report to without a scene?",
   bullets=["What &lsquo;going out&rsquo; is allowed to mean right now, specifically","Where, and with how many other people around","What you actually need to know, as opposed to want to know"]),
 facts=["The information channel is worth more than any rule you can set. Children who expect a calm reaction tell their parents things; children who expect a scene stop reporting, and you find out much later and from someone else.",
        "Your face in the first four seconds decides whether you get told the next thing. Not your policy - your face."],
 scripts=[dict(role="Say", say="I would like to meet them. Not to interrogate anybody - I just want a face to go with the name. And I promise not to make it weird.",
               why="Low stakes, specific, and it names the fear they actually have, which is that you will make it weird."),
          dict(role="The sentence that matters most", say="If anything ever happens that you are not okay with, you can tell me and I will not be angry with you. Not ever, not about that.",
               why="Say it once, early, plainly. It is the single most important sentence in this issue and it has to be in place before it is needed.")],
 dont=dict(say="Ooooh, is this your <em>girlfriend</em>?",
   why="Teasing at fourteen is cheap and closes the channel for years. It is the most expensive joke available to a parent."),
 rule=dict(text="Stay unshockable. React in the morning, not in the moment.",
   why="You can have any opinion you like, later. What you cannot do is have it on your face in the first four seconds."),
 ready=[dict(t="You can hear something surprising without changing your expression", why="This is your readiness test, not theirs."),
        dict(t="They have seen you handle bad news calmly before", why="They are extrapolating from evidence. Give them some."),
        dict(t="You have said the &lsquo;I will not be angry&rsquo; sentence out loud", why="Before it is needed, not during."),
        dict(t="You have agreed what &lsquo;going out&rsquo; means right now", why="Specifically. Vagueness here is not permissiveness, it is just confusion.")],
 notyet="Be specific instead of vague: what is allowed now, what is allowed at sixteen, and when you will talk about it again. &lsquo;We&rsquo;ll see&rsquo; is heard as no, and it costs you the conversation.",
 depth=[("Set the shape, not the rules",
   ["At thirteen or fourteen, &lsquo;going out&rsquo; often means messaging and sitting together at break. Rules built for something more than that are rules about a thing that is not happening, and they read as an accusation.",
    "Ask what it actually means before you legislate. Then agree the shape - group settings, public places, home by a time - rather than an inventory of prohibitions you cannot observe anyway."]),
  ("The conversation nobody wants to have",
   ["Consent, pressure, and what to do when something is not okay. It belongs here, it belongs early, and it belongs in plain language rather than euphemism.",
    "Keep it short and repeat it rarely: nobody is entitled to anything from you, you can stop at any point, and you can ring me from anywhere at any hour and I will come and I will not be angry. Then be someone who would actually do that."])],
 widget=dict(kind="chooser", title="They just told you something. What is your face doing?",
   note="Pick the one you would actually get. The right answer is the same shape every time.",
   data=dict(empty="Pick a scenario.", options=[
     dict(n="1", t="&ldquo;I&rsquo;ve got a boyfriend&rdquo;", head="Say: oh nice, what&rsquo;s he like?",
       body=["Warm, mildly interested, and then let them lead. The temptation is to ask eleven questions; ask one and wait.",
             "Absolutely no teasing, no eyebrow, no reporting it to the rest of the family at dinner as an amusing item. That last one is how you lose the channel."]),
     dict(n="2", t="&ldquo;We broke up&rdquo;", head="Say: ah, that&rsquo;s rubbish. Do you want to talk or not?",
       body=["Offer the conversation and accept no for an answer. First heartbreak is genuinely painful and gets minimised constantly, usually by adults who have forgotten.",
             "Do not say &lsquo;there are plenty more&rsquo; and do not say you never liked them. You may need to like them again next week."]),
     dict(n="3", t="Something that worries you", head="Ask one question. Then wait.",
       body=["Whatever it is, the first four seconds are the whole thing. Keep your face neutral, say &lsquo;right - tell me a bit more&rsquo;, and let the silence do the work.",
             "Have your reaction later, out of the room. Then come back in the morning with a considered response rather than a live one."]),
     dict(n="4", t="Something that frightens you", head="Stay in the room, and get help after",
       body=["Pressure, coercion, an adult, or anything they describe as not okay: your job in that moment is to be calm, to be on their side, and to say clearly that none of it is their fault.",
             "Then get proper help - your doctor, a safeguarding service, or the police as appropriate. What you must not do is react in a way that makes them regret telling you, because that is what determines whether you hear about the next thing."])])),
 kid=dict(scared="You telling them nothing at all.",
   say="Do you want to meet them?",
   dont="Saying nothing. Silence makes grown-ups invent things.",
   job="Tell them one boring true thing early. It buys you privacy about the rest.",
   notyet="Ask exactly what&rsquo;s allowed right now. Exactly.",
   why=["Grown-ups fill silence with the worst thing they can imagine. It&rsquo;s annoying and it&rsquo;s just how they work.",
        "So give them one small, dull, true fact - a name, where you went, that it was fine. It sounds like nothing. It actually buys you a lot of being left alone."],
   steps=["Tell them one boring true thing early, before they ask.",
          "Offer to let them meet the person. It defuses more than almost anything else.",
          "Ask exactly what&rsquo;s allowed right now, so you&rsquo;re not guessing and neither are they."],
   widget=dict(kind="checklist", title="Things worth knowing, whoever you are",
     note="Not about asking permission. Just true.",
     data=dict(empty="Tick the ones you already know are true.",
       items=[dict(t="Nobody is owed anything by me, ever", why="Not for a gift, not for a lift home, not for going out for three months."),
              dict(t="I can stop at any point, including halfway", why="Changing your mind is allowed at any moment. That is what the word means."),
              dict(t="If it feels wrong, that&rsquo;s enough of a reason", why="You don&rsquo;t have to justify it or be sure."),
              dict(t="I can ring home from anywhere, at any hour", why="Ask your grown-up to say this out loud to you. Most will say yes immediately."),
              dict(t="Someone who pressures me is not being nice about it", why="However it&rsquo;s phrased. That is the whole test.")],
       verdicts=[dict(min=5, say="All five. Keep them - they matter more than anything else on this card."),
                 dict(min=3, say="Worth reading the rest again properly. These five are the important bit of this whole page."),
                 dict(min=1, say="Read them all, slowly. And ask your grown-up about the ringing-home one.")])))),
]
